### ISSUE TITLE
Create a vault for carbon protocol v3

### ISSUE THREAD

**Issue by LouGel** [carbonable-labs/carbonable_query_vaults#2]
**Description**
Create a sc vault that batch fetch data for carbon protocol v3. Lower the frequency of fetch in the blockchain.

---
**Acceptance Criteria**
---

- [ ] Make a batch  getter :
    - That takes an array of addresses for every project
    - get all owners with their balance,  for each vintage balance , their status

**Additional context**
---
[ Easy - Cairo / Backend]

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of other projects. I would love to work on this.

**Comment by CollinsC1O** [comment]
May I handle this issue?

**Comment by Unickhub** [comment]
I'd love to work on this!

**Comment by Supa-mega** [comment]
Can I take care of this issue?

**Comment by julienbrs** [comment]
Hi, I'm assigning it to @manlikeHB  as he was the first one to ask. Please join TG to discuss about it if needed: https://t.me/carbonableOD
Issue might be reassigned during ODHack if the contributor drops the isue
You can tag @LouGel for any question on that issue
